(function (root, factory) { if (typeof module === "object" && module.exports) module.exports = factory(); else (root.TSVF = root.TSVF || {}).IntelligenceEngine = factory(); })(typeof globalThis !== "undefined" ? globalThis : this, function () {
  "use strict";
  function clean(v) { return String(v || "").trim(); }
  function pattern(input) { const v = input || {}; const sources = Array.isArray(v.sources) ? v.sources.filter(function (s) { return s && s.id; }) : []; const contradictions = Array.isArray(v.contradictions) ? v.contradictions : []; return { id: v.id || "pattern_" + Date.now().toString(36), name: clean(v.name) || "Untitled pattern", platform: clean(v.platform) || "cross-platform", niche: clean(v.niche), creator: clean(v.creator), format: clean(v.format), hookFamily: clean(v.hookFamily), storyFamily: clean(v.storyFamily), editingFamily: clean(v.editingFamily), visualFamily: clean(v.visualFamily), ctaFamily: clean(v.ctaFamily), sources: sources, sourceCount: sources.length, performanceEvidence: v.performanceEvidence || [], contradictions: contradictions, confidence: sources.length >= 5 && !contradictions.length ? "high" : sources.length >= 2 ? "medium" : "low", lastValidatedAt: v.lastValidatedAt || null, notes: clean(v.notes), recommendedUsage: clean(v.recommendedUsage), risks: (v.risks || []).map(clean).filter(Boolean), limitations: (v.limitations || []).map(clean).filter(Boolean), causalClaim: false }; }
  function summarize(patterns) { const list = patterns || []; const families = Object.create(null); list.forEach(function (p) { const key = p.hookFamily || "unspecified"; (families[key] = families[key] || []).push(p); }); return Object.keys(families).map(function (key) { const group = families[key]; return { hookFamily: key, patternCount: group.length, sourceCount: group.reduce(function (n, p) { return n + (p.sourceCount || 0); }, 0), confidence: group.some(function (p) { return p.confidence === "high"; }) ? "high" : group.some(function (p) { return p.confidence === "medium"; }) ? "medium" : "low", note: "Observed association; effectiveness depends on context and is not established causation." }; }); }
  function dna(subject, patterns) { const list = patterns || []; return { subject: clean(subject) || "Unknown", patternCount: list.length, hookFamilies: Array.from(new Set(list.map(function (p) { return p.hookFamily; }).filter(Boolean))), formatFamilies: Array.from(new Set(list.map(function (p) { return p.format; }).filter(Boolean))), evidenceSources: list.reduce(function (n, p) { return n + (p.sourceCount || 0); }, 0), contradictions: list.reduce(function (all, p) { return all.concat(p.contradictions || []); }, []), limitations: ["DNA describes repeated observed patterns; it does not prove why performance occurred."], generatedAt: new Date().toISOString() }; }
  function blueprint(patterns) { const list = patterns || []; return { inferred: true, ingredients: list.map(function (p) { return { patternId: p.id, hookFamily: p.hookFamily, storyFamily: p.storyFamily, recommendedUsage: p.recommendedUsage, confidence: p.confidence }; }), testRequirement: "Test each ingredient against a control before treating it as reusable.", unsupportedCausation: false }; }
  return { pattern: pattern, summarize: summarize, dna: dna, blueprint: blueprint };
});
