(function (root, factory) { if (typeof module === "object" && module.exports) module.exports = factory(); else (root.TSVF = root.TSVF || {}).Operations = factory(); })(typeof globalThis !== "undefined" ? globalThis : this, function () {
  "use strict";
  const STATUSES = ["idea", "researching", "approved", "scripted", "ready-to-produce", "producing", "ready-to-post", "posted", "measuring", "archived"];
  function clean(v) { return String(v || "").trim(); }
  function uid(prefix) { return prefix + "_" + Date.now().toString(36) + "_" + Math.random().toString(36).slice(2, 8); }
  function project(input) { const v = input || {}; return { id: v.id || uid("project"), name: clean(v.name) || "Untitled project", description: clean(v.description), status: STATUSES.indexOf(v.status) >= 0 ? v.status : "idea", campaignIds: (v.campaignIds || []).filter(Boolean), contentIds: (v.contentIds || []).filter(Boolean), createdAt: v.createdAt || new Date().toISOString(), updatedAt: new Date().toISOString() }; }
  function campaign(input) { const v = input || {}; return { id: v.id || uid("campaign"), projectId: v.projectId || null, name: clean(v.name) || "Untitled campaign", objective: clean(v.objective), platform: clean(v.platform) || "cross-platform", productIds: (v.productIds || []).filter(Boolean), contentIds: (v.contentIds || []).filter(Boolean), startsAt: v.startsAt || null, endsAt: v.endsAt || null, status: STATUSES.indexOf(v.status) >= 0 ? v.status : "idea", createdAt: v.createdAt || new Date().toISOString(), updatedAt: new Date().toISOString() }; }
  function transition(item, next, note) { if (STATUSES.indexOf(next) < 0) throw new Error("Unknown workflow status: " + next); const current = STATUSES.indexOf(item.status), target = STATUSES.indexOf(next); if (next !== "archived" && target < current) throw new Error("Workflow cannot move backwards without creating a new revision"); return Object.assign({}, item, { status: next, updatedAt: new Date().toISOString(), statusHistory: (item.statusHistory || []).concat({ from: item.status, to: next, note: clean(note), at: new Date().toISOString() }) }); }
  function schedule(input) { const v = input || {}; const when = new Date(v.scheduledAt); if (!v.contentId) throw new Error("contentId is required"); if (Number.isNaN(when.getTime())) throw new Error("scheduledAt must be a valid date"); return { id: v.id || uid("slot"), contentId: v.contentId, campaignId: v.campaignId || null, platform: clean(v.platform) || "unknown", scheduledAt: when.toISOString(), timezone: clean(v.timezone) || "UTC", status: "scheduled", notes: clean(v.notes) }; }
  function complianceReview(input) { const v = input || {}; const state = ["pending", "approved", "rejected", "false-positive"].indexOf(v.status) >= 0 ? v.status : "pending"; if (state === "false-positive" && !clean(v.overrideReason)) throw new Error("False-positive overrides require a reason"); return { id: v.id || uid("review"), contentId: v.contentId || null, ruleId: v.ruleId || null, status: state, evidence: clean(v.evidence), overrideReason: clean(v.overrideReason), reviewer: clean(v.reviewer) || "local-user", reviewedAt: new Date().toISOString(), ruleVersion: clean(v.ruleVersion) || "local-v1" }; }
  function compare(records, dimension, metric) { const groups = Object.create(null); (records || []).forEach(function (record) { const key = clean(record.dimensions && record.dimensions[dimension]) || "unknown"; const value = Number(record.metrics && record.metrics[metric]); if (!Number.isFinite(value)) return; const g = groups[key] = groups[key] || { dimensionValue: key, total: 0, count: 0 }; g.total += value; g.count++; }); return Object.keys(groups).map(function (key) { const g = groups[key]; return { dimension: dimension, value: g.dimensionValue, metric: metric, observations: g.count, average: g.total / g.count, causationEstablished: false }; }).sort(function (a, b) { return b.average - a.average; }); }
  function exportProject(projectRecord, database) { const db = database || {}; const campaignIds = projectRecord.campaignIds || []; const contentIds = projectRecord.contentIds || []; return { format: "cif-project-export", version: 1, exportedAt: new Date().toISOString(), project: projectRecord, campaigns: (db.campaigns || []).filter(function (x) { return campaignIds.indexOf(x.id) >= 0 || x.projectId === projectRecord.id; }), contentPacks: (db.contentPacks || []).filter(function (x) { return contentIds.indexOf(x.id) >= 0; }), sources: db.sources || [], compliance: (db.compliance || []).filter(function (x) { return contentIds.indexOf(x.contentId) >= 0; }), note: "Metrics and patterns describe observations and do not establish causation." }; }
  return { STATUSES: STATUSES, project: project, campaign: campaign, transition: transition, schedule: schedule, complianceReview: complianceReview, compare: compare, exportProject: exportProject };
});
