(function (root, factory) { if (typeof module === "object" && module.exports) module.exports = factory(); else (root.TSVF = root.TSVF || {}).YouTubeManualImport = factory(); })(typeof globalThis !== "undefined" ? globalThis : this, function () {
  "use strict";
  function clean(v) { return String(v || "").trim(); }
  function parseUrl(value) { const raw = clean(value); if (!raw) return null; let url; try { url = new URL(raw); } catch (e) { throw new Error("Invalid YouTube URL"); } if (!/(^|\.)youtube\.com$|(^|\.)youtu\.be$/i.test(url.hostname)) throw new Error("URL must use youtube.com or youtu.be"); let videoId = ""; if (/youtu\.be$/i.test(url.hostname)) videoId = url.pathname.split("/").filter(Boolean)[0] || ""; else videoId = url.searchParams.get("v") || (url.pathname.match(/\/(shorts|live|embed)\/([^/?]+)/) || [])[2] || ""; return { url: url.href, kind: videoId ? "video" : "channel", videoId: videoId || null }; }
  function bulkUrls(text) { const seen = Object.create(null); return String(text || "").split(/\r?\n/).map(clean).filter(Boolean).map(parseUrl).filter(function (item) { if (seen[item.url]) return false; seen[item.url] = true; return true; }); }
  function transcript(input) { const v = input || {}; const text = clean(v.text); if (!text) throw new Error("Transcript text is required"); if (text.length > 500000) throw new Error("Transcript exceeds 500,000 characters"); const source = parseUrl(v.sourceUrl); return { id: v.id || "transcript_" + Date.now().toString(36), text: text, language: clean(v.language) || "unknown", sourceUrl: source && source.url, videoId: source && source.videoId, importedAt: new Date().toISOString(), provenance: { method: "manual-paste", suppliedByUser: true, provider: null } }; }
  function metadata(input) { const v = input || {}; const source = parseUrl(v.url); return { title: clean(v.title), channelName: clean(v.channelName), publishedAt: clean(v.publishedAt) || null, durationSeconds: Number(v.durationSeconds) >= 0 ? Number(v.durationSeconds) : null, views: Number(v.views) >= 0 ? Number(v.views) : null, description: clean(v.description), sourceUrl: source && source.url, videoId: source && source.videoId, provenance: { method: "manual-entry", observedAt: v.observedAt || new Date().toISOString() } }; }
  return { parseUrl: parseUrl, bulkUrls: bulkUrls, transcript: transcript, metadata: metadata };
});
